---
- name: "Update apt packages"
  become: true
  apt:
    update_cache: true

- name: "Upgrade packages"
  become: true
  apt:
    upgrade: true

- name: "Remove packages that are no longer used"
  become: true
  apt:
    autoremove: true

- name: "Install dependencies"
  become: true
  apt:
    name: ["unzip", "curl", "git"]
    state: latest
    update_cache: true

- name: "Install latest LTS Node.js and NPM"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash - && sudo apt-get install -y nodejs
    node --version
    npm --version

- name: "Install PM2"
  become: true
  shell: |
    npm i -g pm2